name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U --pre nbdev
          pip install -e ".[dev]"
      - name: Build website
        run: nbdev_docs
      - uses: fastai/workflows/build-docs@master
        with:
          username: jeremyphoward
          hostname: ps625762.dreamhostps.com
          dest_path: docs.fast.ai
          ssh_key: ${{ secrets.DH_KEY }}
          delete: 'yes'

