name: docs
on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types: 
      - completed
  push:
    branches: 
      - master
env:
  HOME: /root
defaults:
  run:
    shell: bash  

jobs:
  build:
    runs-on: ubuntu-20.04
    container: fastai/fastai
    steps:
    - uses: actions/checkout@v2
    - name: Install prereqs
      run: pip install -Uqqq "sentencepiece<0.1.90" pytorch-lightning pytorch-ignite transformers catalyst
    - uses: fastai/workflows/build-docs@master
      with:
        username: jeremyphoward
        hostname: ps625762.dreamhostps.com
        dest_path: fastai.fast.ai
        ssh_key: ${{ secrets.DH_KEY }}
